# WARNING: Under review - generated by LLM.

"""Week 4, Day 4: one visible in-memory checkpoint and resume boundary."""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass

from .generation import Message
from .protocol import AgentError


@dataclass(frozen=True)
class ModelCheckpoint:
    """Small fake-model snapshot needed for deterministic course resumption."""

    conversation_position: int
    response_index: int
    cached_token_ids: tuple[int, ...]
    layer_offsets: tuple[int, ...]

    def __post_init__(self) -> None:
        integers = (self.conversation_position, self.response_index)
        if any(type(value) is not int or value < 0 for value in integers):
            raise AgentError("checkpoint positions must be non-negative integers")
        if any(type(token) is not int or token < 0 for token in self.cached_token_ids):
            raise AgentError("cached token ids must be non-negative integers")
        if not self.layer_offsets or any(
            type(offset) is not int or offset < 0 for offset in self.layer_offsets
        ):
            raise AgentError("checkpoint needs non-negative layer offsets")
        if any(offset != len(self.cached_token_ids) for offset in self.layer_offsets):
            raise AgentError("layer offsets must match the cached token prefix")


@dataclass(frozen=True)
class AgentCheckpoint:
    """Conversation and model state saved after one complete tool observation."""

    checkpoint_id: str
    task: str
    messages: tuple[tuple[str, str], ...]
    model: ModelCheckpoint

    def validate(self) -> None:
        """Reject a checkpoint whose identity or conversation position changed."""

        if not self.task.strip():
            raise AgentError("checkpoint task must not be empty")
        if not self.messages or any(
            not isinstance(message, tuple)
            or len(message) != 2
            or message[0] not in {"system", "user", "assistant"}
            or not isinstance(message[1], str)
            for message in self.messages
        ):
            raise AgentError("checkpoint messages are invalid")
        if self.model.conversation_position != len(self.messages):
            raise AgentError("model checkpoint does not match the conversation")
        if self.checkpoint_id != _checkpoint_id(self.task, self.messages, self.model):
            raise AgentError("checkpoint identity does not match its content")


def _model_payload(model: ModelCheckpoint) -> dict[str, object]:
    return {
        "conversation_position": model.conversation_position,
        "response_index": model.response_index,
        "cached_token_ids": list(model.cached_token_ids),
        "layer_offsets": list(model.layer_offsets),
    }


def _checkpoint_id(
    task: str,
    messages: tuple[tuple[str, str], ...],
    model: ModelCheckpoint,
) -> str:
    payload = {
        "task": task,
        "messages": [list(message) for message in messages],
        "model": _model_payload(model),
    }
    encoded = json.dumps(payload, sort_keys=True, separators=(",", ":")).encode()
    return hashlib.sha256(encoded).hexdigest()


def create_checkpoint(
    task: str, messages: list[Message], model: ModelCheckpoint
) -> AgentCheckpoint:
    """Freeze one conversation boundary and bind it to the fake-model state."""

    if not isinstance(model, ModelCheckpoint):
        raise AgentError("model checkpoint is invalid")
    try:
        frozen_messages = tuple(
            (message["role"], message["content"]) for message in messages
        )
    except (KeyError, TypeError) as error:
        raise AgentError("checkpoint messages are invalid") from error
    checkpoint = AgentCheckpoint(
        _checkpoint_id(task, frozen_messages, model), task, frozen_messages, model
    )
    checkpoint.validate()
    return checkpoint
