# WARNING: Under review - generated by LLM.

"""Week 4, Day 5: compact old effect observations without losing evidence."""

from __future__ import annotations

import json
from collections.abc import Callable, Sequence
from dataclasses import dataclass

from .generation import Message
from .receipts import EffectReceipt

_TOOL_RESULT_PREFIX = "Tool result:\n"


@dataclass(frozen=True)
class CompactionResult:
    """One model-visible transcript and the tokens reclaimed from it."""

    messages: tuple[Message, ...]
    compacted_interactions: int
    tokens_before: int
    tokens_after: int
    receipt_ids: tuple[str, ...]

    @property
    def saved_tokens(self) -> int:
        """Return the exact token reduction reported by the supplied counter."""

        return self.tokens_before - self.tokens_after


def _copy_messages(messages: list[Message]) -> list[Message]:
    copied: list[Message] = []
    for message in messages:
        if (
            not isinstance(message, dict)
            or not isinstance(message.get("role"), str)
            or not isinstance(message.get("content"), str)
        ):
            raise ValueError("messages must contain string role and content fields")
        copied.append({"role": message["role"], "content": message["content"]})
    return copied


def _count_tokens(
    count_tokens: Callable[[list[Message]], int], messages: list[Message]
) -> int:
    count = count_tokens([dict(message) for message in messages])
    if type(count) is not int or count < 0:
        raise ValueError("count_tokens must return a non-negative integer")
    return count


def _completed_interaction(
    action_message: Message, result_message: Message
) -> tuple[str, dict, str] | None:
    if action_message["role"] != "assistant" or result_message["role"] != "user":
        return None
    content = result_message["content"]
    if not content.startswith(_TOOL_RESULT_PREFIX):
        return None
    try:
        action = json.loads(action_message["content"])
    except json.JSONDecodeError:
        return None
    if not isinstance(action, dict) or not isinstance(action.get("tool"), str):
        return None
    return (
        action["tool"],
        {key: value for key, value in action.items() if key != "tool"},
        content[len(_TOOL_RESULT_PREFIX) :],
    )


def _summary(receipt: EffectReceipt, result_preview_chars: int) -> Message:
    result = receipt.result
    if len(result) > result_preview_chars:
        omitted = len(result) - result_preview_chars
        result = f"{result[:result_preview_chars]}… [{omitted} chars omitted]"
    payload = {
        "arguments": receipt.arguments,
        "changed_artifacts": list(receipt.changed_artifacts),
        "exit_state": receipt.exit_state,
        "receipt_id": receipt.receipt_id,
        "result_preview": result,
        "tool": receipt.tool,
    }
    return {
        "role": "user",
        "content": "Completed tool interaction (compacted evidence):\n"
        + json.dumps(payload, sort_keys=True, separators=(",", ":")),
    }


def compact_completed_interactions(
    messages: list[Message],
    receipts: Sequence[EffectReceipt],
    count_tokens: Callable[[list[Message]], int],
    *,
    keep_recent: int = 1,
    result_preview_chars: int = 160,
) -> CompactionResult:
    """Compact old completed effects when their exact receipt matches.

    The input transcript and receipts remain unchanged.  A completed assistant
    action plus tool observation is eligible only when its tool, arguments, and
    full result exactly match a supplied receipt.  Recent eligible interactions
    remain verbatim, and the compacted view is accepted only when the caller's
    model-token counter proves it is smaller.
    """

    if type(keep_recent) is not int or keep_recent < 0:
        raise ValueError("keep_recent must be a non-negative integer")
    if type(result_preview_chars) is not int or result_preview_chars <= 0:
        raise ValueError("result_preview_chars must be a positive integer")

    original = _copy_messages(messages)
    tokens_before = _count_tokens(count_tokens, original)
    unused_receipts = list(receipts)
    if not all(isinstance(receipt, EffectReceipt) for receipt in unused_receipts):
        raise ValueError("receipts must contain EffectReceipt values")

    matched: list[tuple[int, EffectReceipt]] = []
    for index in range(len(original) - 1):
        interaction = _completed_interaction(original[index], original[index + 1])
        if interaction is None:
            continue
        tool, arguments, result = interaction
        for receipt_index, receipt in enumerate(unused_receipts):
            if (
                receipt.tool == tool
                and receipt.arguments == arguments
                and receipt.result == result
            ):
                matched.append((index, receipt))
                unused_receipts.pop(receipt_index)
                break

    compact_count = max(0, len(matched) - keep_recent)
    selected = dict(matched[:compact_count])
    if not selected:
        return CompactionResult(tuple(original), 0, tokens_before, tokens_before, ())

    compacted: list[Message] = []
    receipt_ids: list[str] = []
    index = 0
    while index < len(original):
        receipt = selected.get(index)
        if receipt is None:
            compacted.append(dict(original[index]))
            index += 1
            continue
        compacted.append(dict(original[index]))
        compacted.append(_summary(receipt, result_preview_chars))
        receipt_ids.append(receipt.receipt_id)
        index += 2

    tokens_after = _count_tokens(count_tokens, compacted)
    if tokens_after >= tokens_before:
        return CompactionResult(tuple(original), 0, tokens_before, tokens_before, ())
    return CompactionResult(
        tuple(compacted),
        len(receipt_ids),
        tokens_before,
        tokens_after,
        tuple(receipt_ids),
    )
