# WARNING: Under review - generated by LLM.

"""Week 4, Day 9: keep large tool evidence outside the model context."""

from __future__ import annotations

import hashlib
import json
import os
import re
import tempfile
from dataclasses import dataclass, field
from pathlib import Path

from .protocol import AgentError, ToolAction
from .workspace import ToolPolicy, Workspace

_ARTIFACT_ID = re.compile(r"artifact-[0-9a-f]{64}")
_RANGE_PATH = re.compile(
    r"\.tool-artifacts/(artifact-[0-9a-f]{64})/bytes/([0-9]+)-([0-9]+)"
)


@dataclass(frozen=True)
class ArtifactRef:
    """Identity and size of one exact externalized tool result."""

    artifact_id: str
    byte_count: int
    sha256: str

    def __post_init__(self) -> None:
        if not _ARTIFACT_ID.fullmatch(self.artifact_id):
            raise ValueError("artifact id is invalid")
        if type(self.byte_count) is not int or self.byte_count < 0:
            raise ValueError("artifact byte count must be a non-negative integer")
        if not re.fullmatch(r"[0-9a-f]{64}", self.sha256):
            raise ValueError("artifact digest is invalid")
        if self.artifact_id != f"artifact-{self.sha256}":
            raise ValueError("artifact id must match its digest")


@dataclass
class ArtifactStore:
    """Store exact bytes under one explicit local artifact root."""

    root: Path
    _records: dict[str, ArtifactRef] = field(default_factory=dict, init=False)

    def __post_init__(self) -> None:
        root = Path(self.root)
        if root.is_symlink():
            raise ValueError("artifact root must not be a symlink")
        try:
            root = root.resolve(strict=True)
        except OSError as error:
            raise ValueError("artifact root must exist") from error
        if not root.is_dir():
            raise ValueError("artifact root must be a directory")
        self.root = root

    def put(self, result: str) -> ArtifactRef:
        """Persist one complete UTF-8 tool result and return its identity."""

        if not isinstance(result, str):
            raise ValueError("artifact result must be a string")
        data = result.encode("utf-8")
        digest = hashlib.sha256(data).hexdigest()
        artifact_id = f"artifact-{digest}"
        record = ArtifactRef(artifact_id, len(data), digest)
        path = self.root / artifact_id
        temporary: Path | None = None
        try:
            if not path.exists():
                with tempfile.NamedTemporaryFile(dir=self.root, delete=False) as output:
                    output.write(data)
                    temporary = Path(output.name)
                os.replace(temporary, path)
            elif path.read_bytes() != data:
                raise AgentError("artifact contents conflict with their identity")
        except AgentError:
            raise
        except OSError as error:
            raise AgentError("could not store tool-result artifact") from error
        finally:
            if temporary is not None:
                temporary.unlink(missing_ok=True)
        self._records[artifact_id] = record
        return record

    def read_range(self, artifact_id: str, start: int, end: int) -> bytes:
        """Read one exact half-open byte range from a known artifact."""

        if not isinstance(artifact_id, str) or not _ARTIFACT_ID.fullmatch(artifact_id):
            raise AgentError("artifact id is invalid")
        if type(start) is not int or type(end) is not int:
            raise AgentError("artifact range bounds must be integers")
        if start < 0 or end <= start:
            raise AgentError("artifact range must satisfy 0 <= start < end")
        record = self._records.get(artifact_id)
        if record is None:
            raise AgentError("artifact is not available in this store")
        try:
            data = (self.root / artifact_id).read_bytes()
        except OSError as error:
            raise AgentError("could not read tool-result artifact") from error
        if (
            len(data) != record.byte_count
            or hashlib.sha256(data).hexdigest() != record.sha256
        ):
            raise AgentError("artifact digest does not match its recorded identity")
        if end > len(data):
            raise AgentError("artifact range exceeds the stored byte count")
        return data[start:end]

    def range_path(self, artifact_id: str, start: int, end: int) -> str:
        """Return the virtual read_file path for one explicit byte range."""

        if not isinstance(artifact_id, str) or not _ARTIFACT_ID.fullmatch(artifact_id):
            raise ValueError("artifact id is invalid")
        if type(start) is not int or type(end) is not int or start < 0 or end <= start:
            raise ValueError("artifact range must satisfy 0 <= start < end")
        return f".tool-artifacts/{artifact_id}/bytes/{start}-{end}"


@dataclass
class BoundedEvidenceWorkspace:
    """Bound model-visible results while retaining their exact external bytes."""

    workspace: Workspace
    artifacts: ArtifactStore
    max_inline_bytes: int = 512
    preview_bytes: int = 64
    max_range_bytes: int = 512

    def __post_init__(self) -> None:
        limits = (self.max_inline_bytes, self.preview_bytes, self.max_range_bytes)
        if any(type(limit) is not int or limit <= 0 for limit in limits):
            raise ValueError("evidence limits must be positive integers")
        if self.max_inline_bytes < 512:
            raise ValueError("max_inline_bytes must be at least 512")
        if self.max_range_bytes < 4:
            raise ValueError("max_range_bytes must be at least 4")
        if self.preview_bytes > self.max_inline_bytes:
            raise ValueError("preview_bytes must not exceed max_inline_bytes")

    @property
    def policy(self) -> ToolPolicy:
        """Expose the wrapped policy to the existing system prompt."""

        return self.workspace.policy

    @property
    def available_tools(self) -> frozenset[str]:
        """Reuse exactly the wrapped workspace's existing tool schema."""

        return self.workspace.available_tools

    @property
    def modified_files(self) -> tuple[str, ...]:
        """Expose file-tool changes from the wrapped workspace."""

        return self.workspace.modified_files

    def execute(self, action: ToolAction, tool_call_id: str | None = None) -> str:
        """Execute normally, externalizing only oversized model observations."""

        if action.tool == "read_file":
            raw_path = action.arguments.get("path")
            if isinstance(raw_path, str) and raw_path.startswith(".tool-artifacts/"):
                return self._read_artifact_path(raw_path)
        result = self.workspace.execute(action, tool_call_id)
        data = result.encode("utf-8")
        if result.startswith("error:") or len(data) <= self.max_inline_bytes:
            return result
        record = self.artifacts.put(result)
        return self._bounded_observation(record, data)

    def _bounded_observation(self, record: ArtifactRef, data: bytes) -> str:
        _, suggested_end = self._head_preview(data, self.max_range_bytes)
        for preview_limit in range(self.preview_bytes, -1, -1):
            head, head_end = self._head_preview(data, preview_limit)
            tail, tail_start = self._tail_preview(data, preview_limit, head_end)
            payload = {
                "artifact_id": record.artifact_id,
                "byte_count": record.byte_count,
                "head_preview": head,
                "head_range": [0, head_end],
                "omitted_range": [head_end, tail_start],
                "range_request": {
                    "path": self.artifacts.range_path(
                        record.artifact_id, 0, suggested_end
                    ),
                    "tool": "read_file",
                },
                "sha256": record.sha256,
                "tail_preview": tail,
                "tail_range": [tail_start, record.byte_count],
            }
            observation = "Tool result externalized:\n" + json.dumps(
                payload, ensure_ascii=False, sort_keys=True, separators=(",", ":")
            )
            if len(observation.encode("utf-8")) <= self.max_inline_bytes:
                return observation
        raise AgentError(
            "evidence observation limit is too small for artifact metadata"
        )

    @staticmethod
    def _head_preview(data: bytes, limit: int) -> tuple[str, int]:
        end = min(limit, len(data))
        while end:
            try:
                return data[:end].decode("utf-8"), end
            except UnicodeDecodeError as error:
                end = error.start
        return "", 0

    @staticmethod
    def _tail_preview(data: bytes, limit: int, head_end: int) -> tuple[str, int]:
        start = max(head_end, len(data) - limit)
        while start < len(data):
            try:
                return data[start:].decode("utf-8"), start
            except UnicodeDecodeError as error:
                start += max(1, error.end)
        return "", len(data)

    def _read_artifact_path(self, raw_path: str) -> str:
        match = _RANGE_PATH.fullmatch(raw_path)
        if match is None:
            return "error: artifact range path is malformed"
        artifact_id, raw_start, raw_end = match.groups()
        try:
            start, end = int(raw_start), int(raw_end)
        except ValueError:
            return "error: artifact range path is malformed"
        if end - start > self.max_range_bytes:
            return f"error: artifact range exceeds {self.max_range_bytes} bytes"
        try:
            data = self.artifacts.read_range(artifact_id, start, end)
            text = data.decode("utf-8")
        except UnicodeDecodeError:
            return "error: artifact range does not align to UTF-8 text"
        except AgentError as error:
            return f"error: {error}"
        record = self.artifacts._records[artifact_id]
        payload = {
            "artifact_id": artifact_id,
            "byte_count": len(data),
            "data": text,
            "end": end,
            "sha256": record.sha256,
            "start": start,
            "total_byte_count": record.byte_count,
        }
        return "Artifact range:\n" + json.dumps(
            payload, ensure_ascii=False, sort_keys=True, separators=(",", ":")
        )
