# WARNING: Under review - generated by LLM.

"""Week 4, Day 1: the validated agent loop.

The loop turns model text into one bounded, schema-checked action or final
response.  It stops by budget, returns invalid actions to the model, and
guards against repeated identical actions.  Durable event recording arrives
with Day 3 sessions; this file keeps only the validated Day 1 core.
"""

import json
from collections.abc import Callable
from dataclasses import dataclass
from typing import Any

from .checkpoint import AgentCheckpoint, ModelCheckpoint, create_checkpoint
from .generation import Generate, Message, initial_messages
from .protocol import (
    AgentError,
    AgentAction,
    FinalAction,
    build_system_prompt,
    parse_action,
)


@dataclass(frozen=True)
class AgentLimits:
    """Budgets that guarantee the loop eventually stops."""

    max_steps: int = 8
    max_context_chars: int = 48_000
    max_invalid_actions: int = 3
    max_identical_actions: int = 2

    def __post_init__(self) -> None:
        if (
            min(
                self.max_steps,
                self.max_context_chars,
                self.max_invalid_actions,
                self.max_identical_actions,
            )
            <= 0
        ):
            raise ValueError("agent limits must be positive")


@dataclass(frozen=True)
class AgentEvent:
    """One auditable model/action/tool interaction."""

    step: int
    response: str
    action: AgentAction | None
    result: str | None


@dataclass(frozen=True)
class AgentRun:
    """One bounded run; ``completed`` means the model returned a valid final."""

    completed: bool
    reason: str
    final: str | None
    events: tuple[AgentEvent, ...]
    modified_files: tuple[str, ...] = ()


def _append_tool_result(
    messages: list[Message], response: str, result: str
) -> list[Message]:
    """Append one assistant response and its tool observation."""

    return [
        *messages,
        {"role": "assistant", "content": response},
        {"role": "user", "content": f"Tool result:\n{result}"},
    ]


def _continue_agent(
    messages: list[Message],
    generate: Generate,
    workspace: Any,
    limits: AgentLimits,
    on_event: Callable[[AgentEvent], None] | None,
    *,
    task: str | None = None,
    checkpoint_after_tool_calls: int | None = None,
) -> AgentRun | AgentCheckpoint:
    events: list[AgentEvent] = []
    invalid_actions = 0
    previous_signature: str | None = None
    identical_actions = 0
    tool_calls = 0

    for step in range(1, limits.max_steps + 1):
        if (
            sum(len(message["content"]) for message in messages)
            > limits.max_context_chars
        ):
            return AgentRun(False, "context_limit", None, tuple(events))

        response = generate(messages)
        try:
            action = parse_action(response, workspace.available_tools)
        except AgentError as error:
            invalid_actions += 1
            previous_signature = None
            identical_actions = 0
            result = f"error: {error}"
            event = AgentEvent(step, response, None, result)
            events.append(event)
            if on_event is not None:
                on_event(event)
            if invalid_actions >= limits.max_invalid_actions:
                return AgentRun(False, "invalid_action_limit", None, tuple(events))
            messages = _append_tool_result(messages, response, result)
            continue

        if isinstance(action, FinalAction):
            event = AgentEvent(step, response, action, None)
            events.append(event)
            if on_event is not None:
                on_event(event)
            return AgentRun(True, "completed", action.final, tuple(events))

        signature = json.dumps(
            {"tool": action.tool, **action.arguments}, sort_keys=True
        )
        if signature == previous_signature:
            identical_actions += 1
        else:
            previous_signature = signature
            identical_actions = 1
        if identical_actions > limits.max_identical_actions:
            result = "error: identical action loop detected"
            event = AgentEvent(step, response, action, result)
            events.append(event)
            if on_event is not None:
                on_event(event)
            return AgentRun(False, "repeated_action_limit", None, tuple(events))

        result = workspace.execute(action)
        event = AgentEvent(step, response, action, result)
        events.append(event)
        if on_event is not None:
            on_event(event)
        messages = _append_tool_result(messages, response, result)
        tool_calls += 1
        if checkpoint_after_tool_calls == tool_calls:
            save = getattr(generate, "save_checkpoint", None)
            if save is None:
                raise AgentError("generator does not support checkpoints")
            model = save(messages)
            if not isinstance(model, ModelCheckpoint):
                raise AgentError("generator returned an invalid model checkpoint")
            assert task is not None
            return create_checkpoint(task, messages, model)

    return AgentRun(False, "step_limit", None, tuple(events))


def run_agent(
    task: str | None,
    generate: Generate,
    workspace: Any,
    limits: AgentLimits | None = None,
    on_event: Callable[[AgentEvent], None] | None = None,
) -> AgentRun:
    """Run a bounded validated loop over one task.

    ``workspace`` must expose ``available_tools`` (a frozenset of tool names),
    ``execute(action)`` (returning a result string), and ``modified_files``
    (an iterable of paths).
    """

    if task is None or not task.strip():
        raise ValueError("task must not be empty")
    messages = initial_messages(task, build_system_prompt(workspace))
    result = _continue_agent(
        messages, generate, workspace, limits or AgentLimits(), on_event
    )
    assert isinstance(result, AgentRun)
    return result


def run_to_checkpoint(
    task: str,
    generate: Generate,
    workspace: Any,
    after_tool_calls: int = 1,
    limits: AgentLimits | None = None,
) -> AgentCheckpoint:
    """Run until a tool observation is complete, then save model and messages."""

    if type(after_tool_calls) is not int or after_tool_calls <= 0:
        raise ValueError("after_tool_calls must be a positive integer")
    if not task.strip():
        raise ValueError("task must not be empty")
    messages = initial_messages(task, build_system_prompt(workspace))
    result = _continue_agent(
        messages,
        generate,
        workspace,
        limits or AgentLimits(),
        None,
        task=task,
        checkpoint_after_tool_calls=after_tool_calls,
    )
    if isinstance(result, AgentCheckpoint):
        return result
    raise AgentError(f"run ended before checkpoint: {result.reason}")


def resume_agent(
    checkpoint: AgentCheckpoint,
    generate: Generate,
    workspace: Any,
    limits: AgentLimits | None = None,
) -> AgentRun:
    """Restore a fresh model and continue after the saved tool observation."""

    checkpoint.validate()
    restore = getattr(generate, "restore_checkpoint", None)
    if restore is None:
        raise AgentError("generator does not support checkpoint restore")
    restore(checkpoint.model)
    messages = [
        {"role": role, "content": content} for role, content in checkpoint.messages
    ]
    result = _continue_agent(
        messages, generate, workspace, limits or AgentLimits(), None
    )
    assert isinstance(result, AgentRun)
    return result
