# WARNING: Under review - generated by LLM.

"""Week 4, Day 3: small single-process JSONL effect receipts."""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from .protocol import AgentError


@dataclass(frozen=True)
class EffectReceipt:
    """One completed tool call and its observable outcome."""

    tool_call_id: str
    tool: str
    arguments: dict[str, Any]
    exit_state: str
    result: str
    changed_artifacts: tuple[str, ...] = ()

    def __post_init__(self) -> None:
        if not self.tool_call_id or not self.tool:
            raise ValueError("receipt call id and tool must not be empty")
        if self.exit_state not in {"ok", "error"}:
            raise ValueError("receipt exit_state must be 'ok' or 'error'")
        object.__setattr__(self, "arguments", dict(self.arguments))
        object.__setattr__(self, "changed_artifacts", tuple(self.changed_artifacts))

    def _payload(self) -> dict[str, Any]:
        return {
            "tool_call_id": self.tool_call_id,
            "tool": self.tool,
            "arguments": self.arguments,
            "exit_state": self.exit_state,
            "result": self.result,
            "changed_artifacts": list(self.changed_artifacts),
        }

    @property
    def receipt_id(self) -> str:
        """Return the digest of the canonical receipt payload."""

        encoded = json.dumps(
            self._payload(), sort_keys=True, separators=(",", ":")
        ).encode()
        return hashlib.sha256(encoded).hexdigest()

    def to_dict(self) -> dict[str, Any]:
        """Convert the receipt to its JSON-compatible representation."""

        return {"receipt_id": self.receipt_id, **self._payload()}

    @classmethod
    def from_dict(cls, payload: dict[str, Any]) -> EffectReceipt:
        """Parse and verify one persisted receipt."""

        try:
            expected_id = payload["receipt_id"]
            receipt = cls(
                payload["tool_call_id"],
                payload["tool"],
                payload["arguments"],
                payload["exit_state"],
                payload["result"],
                tuple(payload["changed_artifacts"]),
            )
        except (KeyError, TypeError, ValueError) as error:
            raise AgentError("receipt is malformed") from error
        if set(payload) != {"receipt_id", *receipt._payload()}:
            raise AgentError("receipt is malformed")
        if expected_id != receipt.receipt_id:
            raise AgentError("receipt digest does not match its contents")
        return receipt


@dataclass
class ReceiptStore:
    """Keep receipts in memory and optionally append them to one JSONL file."""

    path: Path | None = None
    _by_call: dict[str, EffectReceipt] = field(default_factory=dict, init=False)

    def __post_init__(self) -> None:
        if self.path is None:
            return
        self.path = Path(self.path)
        if self.path.exists():
            try:
                for line in self.path.read_text(encoding="utf-8").splitlines():
                    receipt = EffectReceipt.from_dict(json.loads(line))
                    previous = self._by_call.get(receipt.tool_call_id)
                    if previous is not None and previous != receipt:
                        raise AgentError("tool call id has conflicting receipts")
                    self._by_call[receipt.tool_call_id] = receipt
            except (OSError, json.JSONDecodeError) as error:
                raise AgentError("could not load receipt log") from error

    def put(self, receipt: EffectReceipt) -> EffectReceipt:
        """Record one call id once; identical retries are idempotent."""

        previous = self._by_call.get(receipt.tool_call_id)
        if previous is not None:
            if previous != receipt:
                raise AgentError("tool call id already has a different receipt")
            return previous
        if self.path is not None:
            try:
                with self.path.open("a", encoding="utf-8") as output:
                    output.write(json.dumps(receipt.to_dict(), sort_keys=True) + "\n")
            except OSError as error:
                raise AgentError("could not append receipt log") from error
        self._by_call[receipt.tool_call_id] = receipt
        return receipt

    def get(self, tool_call_id: str) -> EffectReceipt | None:
        """Return a receipt by tool call id, if present."""

        return self._by_call.get(tool_call_id)
