# WARNING: Under review - generated by LLM.

"""Week 4, Day 6: inspect and steer one paused checkpoint."""

from __future__ import annotations

import json
from dataclasses import dataclass
from typing import Any

from .checkpoint import AgentCheckpoint
from .generation import Generate, Message
from .loop import AgentLimits, AgentRun, _continue_agent
from .protocol import AgentError, ToolAction, parse_action

_TOOL_RESULT_PREFIX = "Tool result:\n"
_STEERING_PREFIX = "Operator steering:\n"


@dataclass(frozen=True)
class AgentStatus:
    """Public facts available at one complete-observation pause."""

    task: str
    last_action: str
    last_evidence: str
    next_step: str


def _bounded_preview(content: str, limit: int) -> str:
    if len(content) <= limit:
        return content
    if limit == 1:
        return "…"
    return content[: limit - 1] + "…"


def _completed_tool_boundary(
    checkpoint: AgentCheckpoint,
) -> tuple[ToolAction, str]:
    checkpoint.validate()
    if len(checkpoint.messages) < 2:
        raise AgentError("checkpoint does not end at a complete tool observation")
    action_role, action_content = checkpoint.messages[-2]
    result_role, result_content = checkpoint.messages[-1]
    if (
        action_role != "assistant"
        or result_role != "user"
        or not result_content.startswith(_TOOL_RESULT_PREFIX)
    ):
        raise AgentError("checkpoint does not end at a complete tool observation")
    try:
        action = parse_action(action_content)
    except AgentError as error:
        raise AgentError(f"checkpoint tool action is invalid: {error}") from error
    if not isinstance(action, ToolAction):
        raise AgentError("checkpoint tool action is invalid: expected a tool action")
    return action, result_content[len(_TOOL_RESULT_PREFIX) :]


def inspect_checkpoint(
    checkpoint: AgentCheckpoint, *, evidence_chars: int = 160
) -> AgentStatus:
    """Derive a bounded public status from a complete tool observation."""

    if type(evidence_chars) is not int or evidence_chars <= 0:
        raise ValueError("evidence_chars must be a positive integer")
    action, evidence = _completed_tool_boundary(checkpoint)
    last_action = json.dumps(
        {"tool": action.tool, **action.arguments},
        sort_keys=True,
        separators=(",", ":"),
    )
    return AgentStatus(
        task=checkpoint.task,
        last_action=last_action,
        last_evidence=_bounded_preview(evidence, evidence_chars),
        next_step=f"resume the model after the completed {action.tool} observation",
    )


def resume_with_steering(
    checkpoint: AgentCheckpoint,
    steering: str,
    generate: Generate,
    workspace: Any,
    limits: AgentLimits | None = None,
) -> AgentRun:
    """Append one visible operator message and resume from the saved prefix."""

    if not isinstance(steering, str) or not steering.strip():
        raise ValueError("steering must not be empty")
    _completed_tool_boundary(checkpoint)
    restore = getattr(generate, "restore_checkpoint", None)
    if restore is None:
        raise AgentError("generator does not support checkpoint restore")
    restore(checkpoint.model)
    messages: list[Message] = [
        {"role": role, "content": content} for role, content in checkpoint.messages
    ]
    messages.append({"role": "user", "content": _STEERING_PREFIX + steering})
    result = _continue_agent(
        messages, generate, workspace, limits or AgentLimits(), None
    )
    assert isinstance(result, AgentRun)
    return result
