# WARNING: Under review - generated by LLM.

"""Week 4, Day 3: inspect, edit, validate, and record a disposable workspace.

This is a teaching boundary for one trusted operator and process, not a sandbox,
transaction log, process jail, or defense against a hostile filesystem.
"""

from __future__ import annotations

import hashlib
import math
import os
import subprocess
import tempfile
from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path

from .protocol import AgentError, ToolAction
from .receipts import EffectReceipt, ReceiptStore

_PROTECTED_NAMES = frozenset(
    {".aws", ".env", ".git", ".ssh", "credentials", "id_ed25519", "id_rsa"}
)
_MAX_COMMAND_OUTPUT_CHARS = 16_000


def _is_protected(path: Path) -> bool:
    return any(
        part.lower() in _PROTECTED_NAMES
        or part.lower().startswith(".env.")
        or part.lower().endswith((".key", ".pem"))
        for part in path.parts
    )


@dataclass(frozen=True)
class ApprovalDecision:
    """One operator approval or a model-visible denial reason."""

    approved: bool
    reason: str = ""

    def __post_init__(self) -> None:
        if type(self.approved) is not bool:
            raise ValueError("approved must be a boolean")
        if not isinstance(self.reason, str):
            raise ValueError("approval reason must be a string")
        if not self.approved and not self.reason.strip():
            raise ValueError("a denial requires a nonblank operator reason")


@dataclass(frozen=True)
class ToolPolicy:
    """Tools and limits authorized for one explicit workspace root."""

    root: Path
    max_file_bytes: int = 64 * 1024
    max_list_entries: int = 200
    allow_writes: bool = False
    allowed_commands: tuple[tuple[str, ...], ...] = ()
    max_write_bytes: int = 64 * 1024
    command_timeout_seconds: float = 30.0

    def __post_init__(self) -> None:
        root = Path(self.root)
        if root.is_symlink():
            raise ValueError("workspace root must not be a symlink")
        try:
            root = root.resolve(strict=True)
        except OSError as error:
            raise ValueError("workspace root must exist") from error
        if not root.is_dir():
            raise ValueError("workspace root must be a directory")
        integer_limits = (
            self.max_file_bytes,
            self.max_list_entries,
            self.max_write_bytes,
        )
        if any(type(limit) is not int or limit <= 0 for limit in integer_limits):
            raise ValueError("workspace limits must be positive integers")
        if type(self.allow_writes) is not bool:
            raise ValueError("allow_writes must be a boolean")
        if (
            type(self.command_timeout_seconds) not in {int, float}
            or self.command_timeout_seconds <= 0
            or not math.isfinite(self.command_timeout_seconds)
        ):
            raise ValueError("command timeout must be finite and positive")
        if not isinstance(self.allowed_commands, tuple):
            raise ValueError("allowed commands must be a tuple of tuples")
        commands = self.allowed_commands
        if any(
            not isinstance(command, tuple)
            or not command
            or any(
                not isinstance(part, str) or not part or "\0" in part
                for part in command
            )
            for command in commands
        ):
            raise ValueError(
                "allowed commands must contain non-empty strings without NUL"
            )
        object.__setattr__(self, "root", root)
        object.__setattr__(self, "allowed_commands", commands)


@dataclass
class Workspace:
    """Run the Day 3 tools under one policy and approval callback."""

    policy: ToolPolicy
    confirm_tool: Callable[[ToolAction], bool | ApprovalDecision] | None = None
    receipt_store: ReceiptStore = field(default_factory=ReceiptStore)
    _observed: dict[str, str] = field(default_factory=dict, init=False)
    _modified: set[str] = field(default_factory=set, init=False)
    _next_call_number: int = field(default=1, init=False)

    @property
    def available_tools(self) -> frozenset[str]:
        tools = {"list_files", "read_file"}
        if self.policy.allow_writes:
            tools.update({"write_file", "edit_file"})
        if self.policy.allowed_commands:
            tools.add("run_command")
        return frozenset(tools)

    @property
    def modified_files(self) -> tuple[str, ...]:
        """Return the files changed by this workspace in sorted order."""

        return tuple(sorted(self._modified))

    def resolve_path(self, raw: str, *, must_exist: bool = True) -> Path:
        """Resolve one relative path without traversal or symlinks."""

        if not isinstance(raw, str) or not raw.strip():
            raise AgentError("path must be a non-empty string")
        relative = Path(raw)
        if relative.is_absolute() or ".." in relative.parts:
            raise AgentError("path must be relative and stay in the workspace")
        if _is_protected(relative):
            raise AgentError("path is not accessible")

        current = self.policy.root
        for part in relative.parts:
            current /= part
            if current.is_symlink():
                raise AgentError("symlinks are not accessible")
        try:
            resolved = current.resolve(strict=must_exist)
            resolved.relative_to(self.policy.root)
        except (OSError, RuntimeError, ValueError) as error:
            raise AgentError("path is not accessible") from error
        return resolved

    def list_files(self, raw: str = ".") -> str:
        """List one directory, bounded by the policy."""

        path = self.resolve_path(raw)
        if not path.is_dir():
            raise AgentError("path is not a directory")
        try:
            children = sorted(path.iterdir(), key=lambda child: child.name)
        except OSError as error:
            raise AgentError(f"could not list path: {error}") from error

        lines: list[str] = []
        for child in children:
            relative = child.relative_to(self.policy.root)
            if child.is_symlink() or _is_protected(relative):
                continue
            kind = "dir" if child.is_dir() else "file" if child.is_file() else None
            if kind is not None:
                lines.append(f"{kind} {relative.as_posix()}")
            if len(lines) == self.policy.max_list_entries:
                break
        return "\n".join(lines) if lines else "(empty directory)"

    def read_file(self, raw: str) -> str:
        """Read one bounded UTF-8 regular file."""

        path = self.resolve_path(raw)
        if not path.is_file():
            raise AgentError("path is not a regular file")
        try:
            if path.stat().st_size > self.policy.max_file_bytes:
                raise AgentError(f"file exceeds {self.policy.max_file_bytes} bytes")
            data = path.read_bytes()
        except AgentError:
            raise
        except OSError as error:
            raise AgentError(f"could not read file: {error}") from error
        if len(data) > self.policy.max_file_bytes:
            raise AgentError(f"file exceeds {self.policy.max_file_bytes} bytes")
        try:
            result = data.decode("utf-8")
        except UnicodeDecodeError as error:
            raise AgentError("file is not valid UTF-8") from error
        self._observed[path.relative_to(self.policy.root).as_posix()] = hashlib.sha256(
            data
        ).hexdigest()
        return result

    def write_file(self, raw: str, content: str) -> str:
        """Atomically create a file or replace one previously read unchanged."""

        path, relative, data = self._prepare_write(raw, content)
        return self._commit(path, relative, data, "wrote")

    def edit_file(self, raw: str, old: str, new: str) -> str:
        """Replace one exact occurrence in a previously read unchanged file."""

        path, relative, data = self._prepare_edit(raw, old, new)
        return self._commit(path, relative, data, "edited")

    def run_command(self, argv: list[str]) -> str:
        """Run one exact allowed argument vector without a shell."""

        command = self._allowed_command(argv)
        try:
            completed = subprocess.run(
                command,
                cwd=self.policy.root,
                capture_output=True,
                text=True,
                timeout=self.policy.command_timeout_seconds,
                check=False,
            )
            status: int | str = completed.returncode
            stdout, stderr = completed.stdout, completed.stderr
        except subprocess.TimeoutExpired as error:
            status = "timeout"
            stdout = error.stdout or ""
            stderr = error.stderr or ""
            if isinstance(stdout, bytes):
                stdout = stdout.decode(errors="replace")
            if isinstance(stderr, bytes):
                stderr = stderr.decode(errors="replace")
        except OSError as error:
            raise AgentError(f"could not run command: {error}") from error
        captured = (stdout + stderr)[:_MAX_COMMAND_OUTPUT_CHARS]
        return f"status: {status}\noutput:\n{captured}"

    def execute(self, action: ToolAction, tool_call_id: str | None = None) -> str:
        """Dispatch one action, approving and receipting effects once."""

        try:
            if action.tool == "list_files":
                return self.list_files(action.arguments.get("path", "."))
            if action.tool == "read_file":
                return self.read_file(action.arguments["path"])
            if action.tool not in self.available_tools:
                raise AgentError(f"tool is not enabled: {action.tool}")
            call_id = tool_call_id or self._new_call_id()
            previous = self.receipt_store.get(call_id)
            if previous is not None:
                if (
                    previous.tool != action.tool
                    or previous.arguments != action.arguments
                ):
                    raise AgentError("tool call id was already used for another action")
                return previous.result

            if action.tool == "write_file":
                self._prepare_write(
                    action.arguments["path"], action.arguments["content"]
                )
            elif action.tool == "edit_file":
                self._prepare_edit(
                    action.arguments["path"],
                    action.arguments["old"],
                    action.arguments["new"],
                )
            else:
                self._allowed_command(action.arguments["argv"])
            decision = self.confirm_tool(action) if self.confirm_tool else False
            if isinstance(decision, ApprovalDecision):
                if not decision.approved:
                    raise AgentError(
                        f"operator denied the tool action: {decision.reason}"
                    )
            elif decision is not True:
                raise AgentError("operator denied the tool action")
            if action.tool == "write_file":
                result = self.write_file(
                    action.arguments["path"], action.arguments["content"]
                )
            elif action.tool == "edit_file":
                result = self.edit_file(
                    action.arguments["path"],
                    action.arguments["old"],
                    action.arguments["new"],
                )
            else:
                result = self.run_command(action.arguments["argv"])
            artifacts = ()
            if action.tool in {"write_file", "edit_file"}:
                path = self.resolve_path(action.arguments["path"])
                artifacts = (path.relative_to(self.policy.root).as_posix(),)
            self.receipt_store.put(
                EffectReceipt(
                    call_id,
                    action.tool,
                    action.arguments,
                    "ok"
                    if action.tool != "run_command" or result.startswith("status: 0\n")
                    else "error",
                    result,
                    artifacts,
                )
            )
            return result
        except (AgentError, KeyError, TypeError) as error:
            return f"error: {error}"

    def _prepare_write(self, raw: str, content: str) -> tuple[Path, str, bytes]:
        if not self.policy.allow_writes:
            raise AgentError("writes are not enabled")
        path = self.resolve_path(raw, must_exist=False)
        relative = path.relative_to(self.policy.root).as_posix()
        if path.exists():
            if not path.is_file():
                raise AgentError("path is not a regular file")
            self._current_observed(path, relative)
        elif not path.parent.is_dir():
            raise AgentError("parent directory does not exist")
        data = content.encode()
        if len(data) > self.policy.max_write_bytes:
            raise AgentError(f"write exceeds {self.policy.max_write_bytes} bytes")
        return path, relative, data

    def _prepare_edit(self, raw: str, old: str, new: str) -> tuple[Path, str, bytes]:
        if not self.policy.allow_writes:
            raise AgentError("writes are not enabled")
        path = self.resolve_path(raw)
        relative = path.relative_to(self.policy.root).as_posix()
        current = self._current_observed(path, relative)
        if not old or current.count(old) != 1:
            raise AgentError("old text must occur exactly once")
        data = current.replace(old, new).encode()
        if len(data) > self.policy.max_write_bytes:
            raise AgentError(f"write exceeds {self.policy.max_write_bytes} bytes")
        return path, relative, data

    def _current_observed(self, path: Path, relative: str) -> str:
        expected = self._observed.get(relative)
        if expected is None:
            raise AgentError("read the existing file before changing it")
        try:
            data = path.read_bytes()
        except OSError as error:
            raise AgentError(f"could not re-read file: {error}") from error
        if hashlib.sha256(data).hexdigest() != expected:
            raise AgentError("file changed since it was read")
        try:
            return data.decode("utf-8")
        except UnicodeDecodeError as error:
            raise AgentError("file is not valid UTF-8") from error

    def _commit(self, path: Path, relative: str, data: bytes, verb: str) -> str:
        temporary: Path | None = None
        try:
            with tempfile.NamedTemporaryFile(dir=path.parent, delete=False) as output:
                output.write(data)
                temporary = Path(output.name)
            os.replace(temporary, path)
        except OSError as error:
            raise AgentError(f"could not replace file: {error}") from error
        finally:
            if temporary is not None:
                temporary.unlink(missing_ok=True)
        self._observed[relative] = hashlib.sha256(data).hexdigest()
        self._modified.add(relative)
        return f"{verb} {relative}"

    def _allowed_command(self, argv: list[str]) -> tuple[str, ...]:
        if not isinstance(argv, list) or any(
            not isinstance(part, str) or not part or "\0" in part for part in argv
        ):
            raise AgentError("argv must contain non-empty strings without NUL")
        command = tuple(argv)
        if command not in self.policy.allowed_commands:
            raise AgentError("command is not allowed")
        return command

    def _new_call_id(self) -> str:
        while True:
            call_id = f"call-{self._next_call_number}"
            self._next_call_number += 1
            if self.receipt_store.get(call_id) is None:
                return call_id
