# WARNING: Under review - generated by LLM.

"""Week 4, Day 8 learner surface for cached branch continuations."""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass
from typing import Any

from .checkpoint import AgentCheckpoint, ModelCheckpoint
from .evaluation import EvaluationCase, EvaluationReport
from .generation import Generate, Message
from .loop import AgentLimits, AgentRun
from .receipts import ReceiptStore
from .workspace import Workspace


@dataclass(frozen=True)
class PrefixReuse:
    """Observable token and cache positions reused by one continuation."""

    reused_tokens: int
    layer_offsets: tuple[int, ...]
    avoided_prefill_tokens: int


@dataclass(frozen=True)
class BranchOutcome:
    """One steered branch, its observable evaluation, and prefix reuse."""

    name: str
    steering: str
    run: AgentRun
    report: EvaluationReport
    reuse: PrefixReuse


class KvPrefixGenerator:
    """Greedy course-model generation from one frozen dense KV prefix."""

    def __init__(
        self,
        model: Any,
        tokenizer: Any,
        max_tokens: int,
        enable_thinking: bool = False,
    ) -> None:
        pass

    @property
    def reuse(self) -> PrefixReuse:
        """Return the prefix positions used by the latest continuation."""

        pass

    def save_checkpoint(self, messages: list[Message]) -> ModelCheckpoint:
        """Render and prefill one checkpoint prefix exactly once."""

        pass

    def restore_checkpoint(self, checkpoint: ModelCheckpoint) -> None:
        """Bind a fresh continuation to this generator's frozen prefix."""

        pass

    def fork(self) -> KvPrefixGenerator:
        """Create a fresh generator that shares only immutable prefix arrays."""

        pass

    def __call__(self, messages: list[Message]) -> str:
        """Generate one continuation from the restored prefix."""

        pass


def run_branch(
    name: str,
    steering: str,
    checkpoint: AgentCheckpoint,
    generate: Generate,
    workspace: Workspace,
    receipts: ReceiptStore,
    case: EvaluationCase,
    limits: AgentLimits | None = None,
) -> BranchOutcome:
    """Resume, evaluate, and retain the reuse facts for one isolated branch."""

    pass


def select_branch(
    outcomes: Sequence[BranchOutcome], selected_name: str
) -> BranchOutcome:
    """Return one explicitly named passing branch."""

    pass
