# WARNING: Under review - generated by LLM.

"""Week 4, Day 4 learner surface for checkpoint and resume."""

from __future__ import annotations

from dataclasses import dataclass

from .generation import Message


@dataclass(frozen=True)
class ModelCheckpoint:
    """Small fake-model snapshot needed for deterministic course resumption."""

    conversation_position: int
    response_index: int
    cached_token_ids: tuple[int, ...]
    layer_offsets: tuple[int, ...]

    def __post_init__(self) -> None:
        # TODO: validate positions, token ids, and aligned layer offsets.
        pass


@dataclass(frozen=True)
class AgentCheckpoint:
    """Conversation and model state saved after one complete tool observation."""

    checkpoint_id: str
    task: str
    messages: tuple[tuple[str, str], ...]
    model: ModelCheckpoint

    def validate(self) -> None:
        """Reject a checkpoint whose identity or conversation position changed."""

        pass


def create_checkpoint(
    task: str, messages: list[Message], model: ModelCheckpoint
) -> AgentCheckpoint:
    """Freeze one conversation boundary and bind it to the fake-model state."""

    pass
