# WARNING: Under review - generated by LLM.

"""Week 4, Day 5: compact old effect observations without losing evidence."""

from collections.abc import Callable, Sequence
from dataclasses import dataclass

from .generation import Message
from .receipts import EffectReceipt


@dataclass(frozen=True)
class CompactionResult:
    """One model-visible transcript and the tokens reclaimed from it."""

    messages: tuple[Message, ...]
    compacted_interactions: int
    tokens_before: int
    tokens_after: int
    receipt_ids: tuple[str, ...]

    @property
    def saved_tokens(self) -> int:
        """Return the exact token reduction reported by the supplied counter."""

        pass


def compact_completed_interactions(
    messages: list[Message],
    receipts: Sequence[EffectReceipt],
    count_tokens: Callable[[list[Message]], int],
    *,
    keep_recent: int = 1,
    result_preview_chars: int = 160,
) -> CompactionResult:
    """Compact old completed effects when their exact receipt matches."""

    pass
