# WARNING: Under review - generated by LLM.

"""Week 4, Day 1: the minimal generation surface (starter).

Day 1 needs only the message types, the initial conversation messages, and
a single-shot ``generate_response`` helper.

Implement the bodies yourself; use the Day 1 chapter and public tests as the
learner contract.
"""

from collections.abc import Callable, Sequence
from typing import Any


Message = dict[str, str]
Generate = Callable[[list[Message]], str]


def initial_messages(task: str, system_prompt: str) -> list[Message]:
    """Create the durable beginning of an agent conversation."""

    # TODO: reject an empty task; return system + user messages.
    pass


def generate_response(
    model,
    tokenizer,
    messages: list[Message],
    cache_factory: Callable[[], Sequence[Any]],
    max_tokens: int,
    enable_thinking: bool = False,
) -> str:
    """Decode one action with the course model and a fresh cache."""

    # TODO: apply the chat template, decode up to max_tokens with the model,
    # stop at eos, release every cache, and return the decoded text.
    pass
