# WARNING: Under review - generated by LLM.

"""Week 4, Day 1: the validated agent loop (starter).

The loop turns model text into one bounded, schema-checked action or final
response.  It stops by budget, returns invalid actions to the model, and
guards against repeated identical actions.  This file keeps only the
validated Day 1 core.

Implement the bodies yourself; use the Day 1 chapter and public tests as the
learner contract.
"""

from collections.abc import Callable
from dataclasses import dataclass
from typing import Any

from .checkpoint import AgentCheckpoint
from .generation import Generate, Message
from .protocol import (
    AgentAction,
)


@dataclass(frozen=True)
class AgentLimits:
    """Budgets that guarantee the loop eventually stops."""

    max_steps: int = 8
    max_context_chars: int = 48_000
    max_invalid_actions: int = 3
    max_identical_actions: int = 2

    def __post_init__(self) -> None:
        """Reject budgets that could disable a stop condition."""

        # TODO: reject any non-positive budget.
        pass


@dataclass(frozen=True)
class AgentEvent:
    """One auditable model/action/tool interaction."""

    step: int
    response: str
    action: AgentAction | None
    result: str | None


@dataclass(frozen=True)
class AgentRun:
    """One bounded run; ``completed`` means the model returned a valid final."""

    completed: bool
    reason: str
    final: str | None
    events: tuple[AgentEvent, ...]
    modified_files: tuple[str, ...] = ()


def _append_tool_result(
    messages: list[Message], response: str, result: str
) -> list[Message]:
    """Append one assistant response and its tool observation."""

    # TODO: append assistant + "Tool result: ..." user messages.
    pass


def run_agent(
    task: str | None,
    generate: Generate,
    workspace: Any,
    limits: AgentLimits | None = None,
    on_event: Callable[[AgentEvent], None] | None = None,
) -> AgentRun:
    """Run a bounded validated loop over one task.

    ``workspace`` must expose ``available_tools`` (a frozenset of tool names),
    ``execute(action)`` (returning a result string), and ``modified_files``
    (an iterable of paths).
    """

    # TODO: reject an empty task; build the system prompt and initial
    # messages; loop up to max_steps; parse each response with
    # parse_action(response, workspace.available_tools); feed invalid
    # actions back as "error: ..." observations; stop on FinalAction,
    # invalid-action limit, identical-action limit, context limit, and step
    # limit.
    pass


def run_to_checkpoint(
    task: str,
    generate: Generate,
    workspace: Any,
    after_tool_calls: int = 1,
    limits: AgentLimits | None = None,
) -> AgentCheckpoint:
    """Run until a tool observation is complete, then save model and messages."""

    pass


def resume_agent(
    checkpoint: AgentCheckpoint,
    generate: Generate,
    workspace: Any,
    limits: AgentLimits | None = None,
) -> AgentRun:
    """Restore a fresh model and continue after the saved tool observation."""

    pass
