# WARNING: Under review - generated by LLM.

from __future__ import annotations

from dataclasses import dataclass
from typing import Any


class AgentError(ValueError):
    """A recoverable error that can be returned to the model."""


@dataclass(frozen=True)
class FinalAction:
    """Week 4, Day 1: a model response that finishes the task."""

    final: str


@dataclass(frozen=True)
class ToolAction:
    """Week 4, Day 1: one validated tool request from the model."""

    tool: str
    arguments: dict[str, Any]


AgentAction = FinalAction | ToolAction


TOOL_FIELDS: dict[str, tuple[frozenset[str], frozenset[str]]] = {
    "list_files": (frozenset(), frozenset({"path"})),
    "read_file": (frozenset({"path"}), frozenset()),
    "write_file": (frozenset({"path", "content"}), frozenset()),
    "edit_file": (frozenset({"path", "old", "new"}), frozenset()),
    "run_command": (frozenset({"argv"}), frozenset()),
}


def parse_action(
    response: str,
    available_tools: frozenset[str] | None = None,
) -> AgentAction:
    """Week 4, Day 1: strictly parse and validate exactly one JSON action."""

    pass


def build_system_prompt(workspace: Any) -> str:
    """Week 4, Day 1: describe only the tools authorized for this run."""

    pass
