# WARNING: Under review - generated by LLM.

"""Week 4, Day 3 learner surface for effect receipts."""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any


@dataclass(frozen=True)
class EffectReceipt:
    """One completed tool call and its observable outcome."""

    tool_call_id: str
    tool: str
    arguments: dict[str, Any]
    exit_state: str
    result: str
    changed_artifacts: tuple[str, ...] = ()

    def __post_init__(self) -> None:
        # TODO: validate and freeze the receipt payload.
        pass

    @property
    def receipt_id(self) -> str:
        """Return the digest of the canonical receipt payload."""

        pass

    def to_dict(self) -> dict[str, Any]:
        """Convert the receipt to its JSON-compatible representation."""

        pass

    @classmethod
    def from_dict(cls, payload: dict[str, Any]) -> EffectReceipt:
        """Parse and verify one persisted receipt."""

        pass


@dataclass
class ReceiptStore:
    """Keep receipts in memory and optionally append them to one JSONL file."""

    path: Path | None = None
    _by_call: dict[str, EffectReceipt] = field(default_factory=dict, init=False)

    def __post_init__(self) -> None:
        # TODO: load and verify an existing JSONL log.
        pass

    def put(self, receipt: EffectReceipt) -> EffectReceipt:
        """Record one call id once; identical retries are idempotent."""

        pass

    def get(self, tool_call_id: str) -> EffectReceipt | None:
        """Return a receipt by tool call id, if present."""

        pass
