# WARNING: Under review - generated by LLM.

"""Week 4, Day 6: inspect and steer one paused checkpoint."""

from dataclasses import dataclass
from typing import Any

from .checkpoint import AgentCheckpoint
from .generation import Generate
from .loop import AgentLimits, AgentRun


@dataclass(frozen=True)
class AgentStatus:
    """Public facts available at one complete-observation pause."""

    task: str
    last_action: str
    last_evidence: str
    next_step: str


def inspect_checkpoint(
    checkpoint: AgentCheckpoint, *, evidence_chars: int = 160
) -> AgentStatus:
    """Derive a bounded public status from a complete tool observation."""

    pass


def resume_with_steering(
    checkpoint: AgentCheckpoint,
    steering: str,
    generate: Generate,
    workspace: Any,
    limits: AgentLimits | None = None,
) -> AgentRun:
    """Append one visible operator message and resume from the saved prefix."""

    pass
