# WARNING: Under review - generated by LLM.

"""Week 4, Day 3 learner surface for workspace effects."""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path

from .protocol import ToolAction
from .receipts import ReceiptStore


@dataclass(frozen=True)
class ApprovalDecision:
    """One operator approval or a model-visible denial reason."""

    approved: bool
    reason: str = ""

    def __post_init__(self) -> None:
        # TODO: validate the decision and require a reason for denials.
        pass


@dataclass(frozen=True)
class ToolPolicy:
    """Tools and limits authorized for one explicit workspace root."""

    root: Path
    max_file_bytes: int = 64 * 1024
    max_list_entries: int = 200
    allow_writes: bool = False
    allowed_commands: tuple[tuple[str, ...], ...] = ()
    max_write_bytes: int = 64 * 1024
    command_timeout_seconds: float = 30.0

    def __post_init__(self) -> None:
        # TODO: normalize and validate the root and positive limits.
        pass


@dataclass
class Workspace:
    """Run the Day 3 tools under one policy and approval callback."""

    policy: ToolPolicy
    confirm_tool: Callable[[ToolAction], bool | ApprovalDecision] | None = None
    receipt_store: ReceiptStore = field(default_factory=ReceiptStore)
    _observed: dict[str, str] = field(default_factory=dict, init=False)
    _modified: set[str] = field(default_factory=set, init=False)
    _next_call_number: int = field(default=1, init=False)

    @property
    def available_tools(self) -> frozenset[str]:
        """Return only the tools enabled by this policy."""

        pass

    @property
    def modified_files(self) -> tuple[str, ...]:
        """Return the files changed by this workspace in sorted order."""

        pass

    def resolve_path(self, raw: str, *, must_exist: bool = True) -> Path:
        """Resolve one relative path without traversal or symlinks."""

        pass

    def list_files(self, raw: str = ".") -> str:
        """List one directory, bounded by the policy."""

        pass

    def read_file(self, raw: str) -> str:
        """Read one bounded UTF-8 regular file."""

        pass

    def write_file(self, raw: str, content: str) -> str:
        """Atomically create a file or replace one previously read unchanged."""

        pass

    def edit_file(self, raw: str, old: str, new: str) -> str:
        """Replace one exact occurrence in a previously read unchanged file."""

        pass

    def run_command(self, argv: list[str]) -> str:
        """Run one exact allowed argument vector without a shell."""

        pass

    def execute(self, action: ToolAction, tool_call_id: str | None = None) -> str:
        """Dispatch one action, approving and receipting effects once."""

        pass
